baseURL = "https://www.guangyuanweng.com/"

googleAnalytics = "G-8Y08N3DM03"

languageCode = "en-us"

# for using avicenna you need to set the themes to 'avicenna'
enableEmoji = true
theme = "avicenna"

# This is your page title, it appears in your tab
title = "Guangyuan Weng's Homepage"

# number of posts to show on the blog page
[pagination]
pagerSize = 10

# suppress raw HTML warning
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
[markup.goldmark.renderer]
# allow raw HTML in content (own-authored site)
unsafe = true

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[params]
# it is used for the copy-right section of your page
name = "Guangyuan Weng"
